### ISSUE TITLE
Plus d'information quant à la création de l'application Slack svp

### ISSUE THREAD

**Issue by Naereen** [loicbourg/kaamelott-soundboard-slack#2]
Salut,
J'ai essayé pendant un bon moment de reproduire les dernières étapes de l'installation :
- l'app tourne localement sur localhost:3333
- j'ai utilisé ngrok pour l'exposer à une adresse accessible de n'importe où : genre xxx.ngrok.io
- j'ai créé l'application sur Slack, avec les autorisations demandées, je la vois activée dans un canal `#test` de mon équipe Slack
- j'ai donné les permissions conseillées (`files:write:user`, `links:read`)
- mais l'événement `link_shared` n'est pas disponible dans "Subscribe to Workspace Events"... alors que la permission `links:read` est bonne. J'ai juste `file_shared` parmi les événements que je peux choisir.

Des idées quant à ce que je fais mal ?

Si possible il faudrait améliorer les explications, avec des captures d'écran étape par étape par exemple.

Et notamment il doit manquer quelque chose, puis dans les 4 étapes dans Readme.md rien ne précise quand/où il faut ajouter l'URL de l'application (mon xxx.ngrok.io ici) !

**Comment by Naereen** [comment]
Avec l'interface de contrôle de ngrok, je vois que des requêtes sont faites depuis Slack, donc tout semble bien connecté d'un point de vue réseau...

**Comment by Naereen** [comment]
Mais les seules requêtes sont des "POST /" sans rien d'autre.

**Comment by loicbourg** [comment]
je pense avoir compris le problème:

En fait c'est en ajoutant le domaine http://kaamelott-soundboard.2ec0b4.fr/ via  `App Unfurl Domains` que ca va ajouter l'event `link_shared` dans les evenements souscrits par l'application.

![slack](https://user-images.githubusercontent.com/4905942/32415272-59350ef8-c237-11e7-8e67-87ca8e11deba.png)


Je vais m'occuper de refaire la partie configuration du Readme pour clarifier tout ca.

**Comment by Naereen** [comment]
Ah étrange, je l'avais pas moi :-/
Je retenterai après les explications mises à jour, merci.

**Comment by loicbourg** [comment]
@Naereen j'ai mis à jour le readme.

 Hésite pas à fermer l'issue si tu réussis à installer l'application avec ces explications ;)

**Comment by Naereen** [comment]
Salut @loicbourg, désolé je n'étais jamais revenu sur ça.
Je n'utilise plus Slack depuis 2017, donc on peut fermer cela.
A+ !
