### ISSUE TITLE
Unfulr URL au lieu d'ajouter un fichier ?

### ISSUE THREAD

**Issue by Naereen** [loicbourg/kaamelott-soundboard-slack#3]
https://api.slack.com/docs/message-link-unfurling#slack_app_unfurling peut aussi être intéressant.

**Comment by loicbourg** [comment]
@Naereen oui c'etait mon idée de depart. 

Mais malheureusement l'unfurl ne permet pas d'afficher de lecteur (j'avais trouvé un long fil twitter de 2014 qui en parlait et qui était encore alimenté aujourd'hui)

**Comment by Naereen** [comment]
OK
